/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser";

export type * from "../models";
export type * from "./prismaNamespace";

export const Decimal = runtime.Decimal;

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (
    secret: never,
  ) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (
    secret: never,
  ) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (
    secret: never,
  ) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

export const ModelName = {
  Session: "Session",
  SystemUser: "SystemUser",
  WorkspaceUser: "WorkspaceUser",
  Workspace: "Workspace",
  SystemEvent: "SystemEvent",
  WorkspaceEvent: "WorkspaceEvent",
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable",
} as const);

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const SessionScalarFieldEnum = {
  id: "id",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  revokeReason: "revokeReason",
  isValid: "isValid",
  systemUserId: "systemUserId",
  workspaceUserId: "workspaceUserId",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  expiresAt: "expiresAt",
  accessedAt: "accessedAt",
  revokeAt: "revokeAt",
} as const;

export type SessionScalarFieldEnum =
  (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum];

export const SystemUserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  password: "password",
  isVerified: "isVerified",
  role: "role",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type SystemUserScalarFieldEnum =
  (typeof SystemUserScalarFieldEnum)[keyof typeof SystemUserScalarFieldEnum];

export const WorkspaceUserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  password: "password",
  isVerified: "isVerified",
  role: "role",
  workspaceId: "workspaceId",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type WorkspaceUserScalarFieldEnum =
  (typeof WorkspaceUserScalarFieldEnum)[keyof typeof WorkspaceUserScalarFieldEnum];

export const WorkspaceScalarFieldEnum = {
  id: "id",
  domain: "domain",
  name: "name",
  description: "description",
  creatorId: "creatorId",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type WorkspaceScalarFieldEnum =
  (typeof WorkspaceScalarFieldEnum)[keyof typeof WorkspaceScalarFieldEnum];

export const SystemEventScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  systemUserId: "systemUserId",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type SystemEventScalarFieldEnum =
  (typeof SystemEventScalarFieldEnum)[keyof typeof SystemEventScalarFieldEnum];

export const WorkspaceEventScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  workspaceUserId: "workspaceUserId",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type WorkspaceEventScalarFieldEnum =
  (typeof WorkspaceEventScalarFieldEnum)[keyof typeof WorkspaceEventScalarFieldEnum];

export const SortOrder = {
  asc: "asc",
  desc: "desc",
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const QueryMode = {
  default: "default",
  insensitive: "insensitive",
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
  first: "first",
  last: "last",
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];
