/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const SystemUserRole = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  USER: "USER",
} as const;

export type SystemUserRole =
  (typeof SystemUserRole)[keyof typeof SystemUserRole];

export const WorkspaceUserRole = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  USER: "USER",
} as const;

export type WorkspaceUserRole =
  (typeof WorkspaceUserRole)[keyof typeof WorkspaceUserRole];
